import { db } from './database.js';
import { t } from './translations.js';
import { esc, attr, formatDate, formatNumber, badge, actionButtons, todayISO, toSolarDate, printTable } from './utils.js';
import { moduleHeader, toolbar, tableHtml, openEntityForm, openRecordDetails, removeEntity, memberSelectOptions, madrasaSelectOptions, memberNames, madrasaNames, idsOf, dutyStatusOptions, priorityOptions } from './moduleHelpers.js';

function fields(members,madrasas) { return [
  {type:'section',label:'duties'}, {key:'title',label:'dutyTitle',required:true}, {key:'description',label:'description',type:'textarea'},
  {key:'assignedMembers',label:'assignedMember',type:'multi-select',options:() => memberSelectOptions(members,'',true),required:true},
  {key:'date',label:'date',type:'date',required:true}, {key:'deadline',label:'deadline',type:'date',required:true},
  {key:'madrasaIds',label:'relatedMadrasa',type:'multi-select',options:() => madrasaSelectOptions(madrasas)},
  {key:'priority',label:'priority',type:'select',options:priorityOptions,default:'medium'}, {key:'status',label:'status',type:'select',options:dutyStatusOptions,default:'pending'},
  {key:'completionDate',label:'completionDate',type:'date'}, {key:'result',label:'result',type:'textarea'}, {key:'notes',label:'notes',type:'textarea'}
]; }

export async function render(ctx) {
  const [duties,members,madrasas] = await Promise.all(['duties','members','madrasas'].map(s => db.getAll(s)));
  const q = ctx.params?.q || '';
  const filtered = q ? duties.filter(d => [d.title,d.description,d.status,d.result].some(v => String(v || '').toLocaleLowerCase().includes(q.toLocaleLowerCase()))) : duties;
  const rows = filtered.slice().sort((a,b) => String(a.deadline || '').localeCompare(String(b.deadline || ''))).map(d => {
    const assigned = memberNames(members,d,'assignedMembers','assignedMember');
    const madrasa = madrasaNames(madrasas,d,'madrasaIds','madrasaId');
    const overdue = d.status !== 'completed' && d.status !== 'cancelled' && d.deadline && toSolarDate(d.deadline) < todayISO();
    return `<tr data-row-search="${attr([d.title,d.description,d.status,assigned,madrasa].join(' '))}" data-members="${attr(idsOf(d,'assignedMembers','assignedMember').join('|'))}"><td><strong>${esc(d.title || '—')}</strong><small>${esc(d.description || '')}</small></td><td>${esc(assigned)}</td><td>${esc(formatDate(d.date))}</td><td class="${overdue ? 'text-danger' : ''}">${esc(formatDate(d.deadline))}${overdue ? `<small style="color:var(--danger)">${esc(t('delayed'))}</small>` : ''}</td><td>${esc(madrasa)}</td><td>${badge(t(d.priority,d.priority || '—'))}</td><td>${badge(t(d.status,d.status || '—'))}</td><td>${actionButtons(d.id,{store:'duties'})}</td></tr>`;
  });
  return `${moduleHeader('duties',`${formatNumber(duties.length)} ${t('duties')}`,`<button class="btn primary" data-duties-action="add">＋ ${esc(t('addDuty'))}</button><button class="btn outline" data-duties-action="print">⎙ ${esc(t('print'))}</button><button class="btn outline" data-duties-action="export">⇩ ${esc(t('exportExcel'))}</button>`)}<section class="card">${toolbar(t('search'),`<select class="select-control" data-duty-view><option value="all">${esc(t('all'))}</option><option value="mine">${esc(t('myDuties'))}</option><option value="today">${esc(t('today'))}</option><option value="overdue">${esc(t('delayed'))}</option><option value="upcoming">${esc(t('upcomingDuties'))}</option><option value="completed">${esc(t('completedDuties'))}</option></select><select class="select-control" data-duty-member><option value="">${esc(t('allMembers'))}</option>${memberSelectOptions(members).map(o => `<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select><select class="select-control" data-duty-status><option value="">${esc(t('status'))}</option>${dutyStatusOptions().map(o => `<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select>`)}<div class="table-summary">${dutyStatusOptions().map(o => `<div class="mini-stat"><div class="mini-value">${esc(formatNumber(duties.filter(d => d.status === o.value).length))}</div><div class="mini-label">${esc(o.label)}</div></div>`).join('')}</div>${tableHtml([t('dutyTitle'),t('assignedMember'),t('date'),t('deadline'),t('relatedMadrasa'),t('priority'),t('status'),t('actions')],rows,t('noData'),`<button class="btn primary small" data-duties-action="add">＋ ${esc(t('addDuty'))}</button>`)}</section>`;
}

export async function bind(ctx,root) {
  const filter = () => { const q=(root.querySelector('[data-module-search]')?.value || '').toLocaleLowerCase(), status=root.querySelector('[data-duty-status]')?.value || '', view=root.querySelector('[data-duty-view]')?.value || 'all', member=root.querySelector('[data-duty-member]')?.value || ''; root.querySelectorAll('[data-row-search]').forEach(row => { const text=row.textContent.toLocaleLowerCase(); let okView=true; if(view==='today') okView=text.includes(formatDate(todayISO()).toLocaleLowerCase()) || text.includes(todayISO()); if(view==='overdue') okView=text.includes(t('delayed').toLocaleLowerCase()); if(view==='completed') okView=text.includes(t('completed').toLocaleLowerCase()); if(view==='upcoming') okView=!text.includes(t('completed').toLocaleLowerCase()) && !text.includes(t('delayed').toLocaleLowerCase()); const memberOk=!member || row.dataset.members.split('|').includes(member); row.style.display=(!q || row.dataset.rowSearch.toLocaleLowerCase().includes(q)) && (!status || text.includes(t(status).toLocaleLowerCase())) && okView && memberOk ? '' : 'none'; }); };
  root.querySelector('[data-module-search]')?.addEventListener('input',filter); root.querySelector('[data-duty-view]')?.addEventListener('change',filter); root.querySelector('[data-duty-member]')?.addEventListener('change',filter); root.querySelector('[data-duty-status]')?.addEventListener('change',filter);
  root.addEventListener('click',async e => { const el=e.target.closest('[data-duties-action]'); if(el){const action=el.dataset.dutiesAction;if(action==='add')return openDuty(ctx);if(action==='export')return ctx.export('duties');if(action==='print'){const duties=await db.getAll('duties');return ctx.printOfficial(t('duties'),`<div class="print-section"><h3>${esc(t('duties'))}</h3>${printTable([t('dutyTitle'),t('date'),t('deadline'),t('status'),t('result')],duties.map(d=>[d.title,formatDate(d.date),formatDate(d.deadline),t(d.status,d.status),d.result || '—']))}</div>`);}} const btn=e.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action,id=btn.dataset.id;if(action==='view')return openRecordDetails(ctx,'duties',id);if(action==='edit')return openDuty(ctx,id);if(action==='delete')return removeEntity(ctx,'duties',id); });
}
async function openDuty(ctx,id='') { const [duties,members,madrasas]=await Promise.all(['duties','members','madrasas'].map(s => db.getAll(s))); const source=id ? duties.find(d => d.id===id) || {} : {}; const record={...source,date:source.date || todayISO(),deadline:source.deadline || todayISO(),assignedMembers:idsOf(source,'assignedMembers','assignedMember'),madrasaIds:idsOf(source,'madrasaIds','madrasaId')}; return openEntityForm(ctx,{store:'duties',title:id ? `${t('edit')} · ${t('duties')}` : t('addDuty'),record,fields:fields(members,madrasas),wide:true,beforeSave:data => {data.assignedMembers=Array.isArray(data.assignedMembers)?data.assignedMembers.filter(Boolean):[];data.assignedMember=data.assignedMembers[0] || '';data.madrasaIds=Array.isArray(data.madrasaIds)?data.madrasaIds.filter(Boolean):[];data.madrasaId=data.madrasaIds[0] || '';if(data.status==='completed'&&!data.completionDate)data.completionDate=todayISO();return data;}}); }
export async function autoAdd(ctx) { return openDuty(ctx); }
