import { db } from './database.js';
import { t } from './translations.js';
import { esc, attr, formatDate, formatNumber, badge, actionButtons, printTable, todayISO } from './utils.js';
import { moduleHeader, toolbar, tableHtml, openEntityForm, openRecordDetails, removeEntity, memberSelectOptions, madrasaSelectOptions, memberNames, madrasaNames, idsOf } from './moduleHelpers.js';

const typeOptions = () => ['monitoringVisit','teacherTraining','seminar','workshop','meeting','consultation','teacherSupport','assessment','coordination','other'].map(k => ({value:k,label:t(k)}));
const activityStatus = () => [{value:'planned',label:t('planned')},{value:'inProgress',label:t('inProgress')},{value:'completed',label:t('completedTasks')},{value:'cancelled',label:t('cancelled')}];
function fields(members,madrasas) { return [
  {type:'section',label:'activities'}, {key:'title',label:'activityTitle',required:true}, {key:'activityType',label:'activityType',type:'select',options:typeOptions,required:true}, {key:'date',label:'date',type:'date',required:true}, {key:'location',label:'location'},
  {key:'madrasaIds',label:'relatedMadrasa',type:'multi-select',options:() => madrasaSelectOptions(madrasas)}, {key:'responsibleMembers',label:'responsibleMember',type:'multi-select',options:() => memberSelectOptions(members,'',true)},
  {key:'participants',label:'participants',type:'textarea'}, {key:'description',label:'description',type:'textarea',span:2}, {key:'results',label:'results',type:'textarea'}, {key:'problems',label:'problems',type:'textarea'}, {key:'recommendations',label:'recommendations',type:'textarea'}, {key:'status',label:'status',type:'select',options:activityStatus,default:'completed'}, {key:'notes',label:'notes',type:'textarea',span:2}
]; }

export async function render(ctx) {
  const [activities,members,madrasas] = await Promise.all(['activities','members','madrasas'].map(s => db.getAll(s)));
  const q=ctx.params?.q || ''; const filtered=q ? activities.filter(a => [a.title,a.activityType,a.description,a.results].some(v => String(v || '').toLocaleLowerCase().includes(q.toLocaleLowerCase()))) : activities;
  const rows=filtered.slice().sort((a,b) => String(b.date || '').localeCompare(String(a.date || ''))).map(a => { const responsible=memberNames(members,a,'responsibleMembers','responsibleMember'), madrasa=madrasaNames(madrasas,a,'madrasaIds','madrasaId'); return `<tr data-row-search="${attr([a.title,a.activityType,a.description,a.results,responsible,madrasa].join(' '))}"><td><strong>${esc(a.title || '—')}</strong><small>${esc(t(a.activityType,a.activityType) || '—')}</small></td><td>${esc(formatDate(a.date))}</td><td>${esc(t(a.activityType,a.activityType) || '—')}</td><td>${esc(a.location || '—')}</td><td>${esc(responsible)}</td><td>${esc(madrasa)}</td><td>${badge(t(a.status,a.status || '—'))}</td><td>${actionButtons(a.id,{store:'activities'})}</td></tr>`; });
  return `${moduleHeader('activities',`${formatNumber(activities.length)} ${t('activities')}`,`<button class="btn primary" data-activities-action="add">＋ ${esc(t('addActivity'))}</button><button class="btn outline" data-activities-action="print">⎙ ${esc(t('print'))}</button><button class="btn outline" data-activities-action="export">⇩ ${esc(t('exportExcel'))}</button>`)}<section class="card">${toolbar(t('search'),`<select class="select-control" data-activity-type><option value="">${esc(t('activityType'))}</option>${typeOptions().map(o => `<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select><select class="select-control" data-activity-status><option value="">${esc(t('status'))}</option>${activityStatus().map(o => `<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select>`)}<div class="table-summary">${typeOptions().slice(0,5).map(o => `<div class="mini-stat"><div class="mini-value">${esc(formatNumber(activities.filter(a => a.activityType === o.value).length))}</div><div class="mini-label">${esc(o.label)}</div></div>`).join('')}</div>${tableHtml([t('activityTitle'),t('date'),t('activityType'),t('location'),t('responsibleMember'),t('relatedMadrasa'),t('status'),t('actions')],rows,t('noData'),`<button class="btn primary small" data-activities-action="add">＋ ${esc(t('addActivity'))}</button>`)}</section>`;
}
export async function bind(ctx,root) { const filter=()=>{const q=(root.querySelector('[data-module-search]')?.value || '').toLocaleLowerCase(),type=root.querySelector('[data-activity-type]')?.value || '',status=root.querySelector('[data-activity-status]')?.value || '';root.querySelectorAll('[data-row-search]').forEach(row=>{const txt=row.dataset.rowSearch.toLocaleLowerCase(),text=row.textContent.toLocaleLowerCase();row.style.display=(!q || txt.includes(q)) && (!type || text.includes(t(type).toLocaleLowerCase())) && (!status || text.includes(t(status).toLocaleLowerCase())) ? '' : 'none';});}; root.querySelector('[data-module-search]')?.addEventListener('input',filter);root.querySelector('[data-activity-type]')?.addEventListener('change',filter);root.querySelector('[data-activity-status]')?.addEventListener('change',filter);root.addEventListener('click',async e=>{const el=e.target.closest('[data-activities-action]');if(el){const action=el.dataset.activitiesAction;if(action==='add')return openActivity(ctx);if(action==='export')return ctx.export('activities');if(action==='print'){const rows=await db.getAll('activities');return ctx.printOfficial(t('activities'),`<div class="print-section"><h3>${esc(t('activities'))}</h3>${printTable([t('activityTitle'),t('activityType'),t('date'),t('location'),t('status')],rows.map(x=>[x.title,t(x.activityType,x.activityType),formatDate(x.date),x.location || '—',t(x.status,x.status)]))}</div>`);}}const btn=e.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action,id=btn.dataset.id;if(action==='view')return openRecordDetails(ctx,'activities',id);if(action==='edit')return openActivity(ctx,id);if(action==='delete')return removeEntity(ctx,'activities',id);}); }
async function openActivity(ctx,id='') { const [activities,members,madrasas]=await Promise.all(['activities','members','madrasas'].map(s => db.getAll(s))); const source=id ? activities.find(a => a.id===id) || {} : {}; const record={...source,date:source.date || todayISO(),status:source.status || 'completed',responsibleMembers:idsOf(source,'responsibleMembers','responsibleMember'),madrasaIds:idsOf(source,'madrasaIds','madrasaId')}; return openEntityForm(ctx,{store:'activities',title:id ? `${t('edit')} · ${t('activities')}` : t('addActivity'),record,fields:fields(members,madrasas),wide:true,beforeSave:data => {data.responsibleMembers=Array.isArray(data.responsibleMembers)?data.responsibleMembers.filter(Boolean):[];data.responsibleMember=data.responsibleMembers[0] || '';data.madrasaIds=Array.isArray(data.madrasaIds)?data.madrasaIds.filter(Boolean):[];data.madrasaId=data.madrasaIds[0] || '';return data;}}); }
export async function autoAdd(ctx) { return openActivity(ctx); }
