import { downloadBlob, esc, slug } from './utils.js';

const xmlEscape = value => String(value ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');
function crc32(bytes) { let table = crc32.table; if (!table) { table = crc32.table = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = (c & 1) ? (0xedb88320 ^ (c >>> 1)) : (c >>> 1); table[n] = c >>> 0; } } let c = 0xffffffff; for (const byte of bytes) c = table[(c ^ byte) & 0xff] ^ (c >>> 8); return (c ^ 0xffffffff) >>> 0; }
function u16(n) { return new Uint8Array([n & 255, (n >>> 8) & 255]); }
function u32(n) { return new Uint8Array([n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255]); }
function concat(parts) { const size = parts.reduce((s, p) => s + p.length, 0); const out = new Uint8Array(size); let offset = 0; parts.forEach(p => { out.set(p, offset); offset += p.length; }); return out; }
function zipStore(files) { const encoder = new TextEncoder(); const local = []; const central = []; let offset = 0; for (const [name, content] of Object.entries(files)) { const nameBytes = encoder.encode(name); const data = encoder.encode(content); const crc = crc32(data); const head = concat([new Uint8Array([0x50,0x4b,0x03,0x04]), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length), u16(nameBytes.length), u16(0), nameBytes]); local.push(head, data); const cen = concat([new Uint8Array([0x50,0x4b,0x01,0x02]), u16(20), u16(20), u16(0), u16(0), u16(0), u16(0), u32(crc), u32(data.length), u32(data.length), u16(nameBytes.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), nameBytes]); central.push(cen); offset += head.length + data.length; } const centralBytes = concat(central); const localBytes = concat(local); const end = concat([new Uint8Array([0x50,0x4b,0x05,0x06]), u16(0), u16(0), u16(central.length), u16(central.length), u32(centralBytes.length), u32(localBytes.length), u16(0)]); return concat([localBytes, centralBytes, end]); }
function colName(index) { let name = ''; let n = index + 1; while (n) { const rem = (n - 1) % 26; name = String.fromCharCode(65 + rem) + name; n = Math.floor((n - 1) / 26); } return name; }
function cell(value, ref) { if (value === null || value === undefined || value === '') return `<c r="${ref}"/>`; if (typeof value === 'number' && Number.isFinite(value)) return `<c r="${ref}"><v>${value}</v></c>`; return `<c r="${ref}" t="inlineStr"><is><t>${xmlEscape(value)}</t></is></c>`; }
function sheetXml(rows) { const safeRows = Array.isArray(rows) ? rows : []; const body = safeRows.map((row, r) => `<row r="${r + 1}">${(Array.isArray(row) ? row : [row]).map((v, c) => cell(v, `${colName(c)}${r + 1}`)).join('')}</row>`).join(''); const width = Math.max(1, ...safeRows.map(r => Array.isArray(r) ? r.length : 1)); return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${colName(width - 1)}${Math.max(1, safeRows.length)}"/><sheetViews><sheetView workbookViewId="0" rightToLeft="1"/></sheetViews><sheetFormatPr defaultRowHeight="18"/><sheetData>${body}</sheetData><autoFilter ref="A1:${colName(width - 1)}${Math.max(1, safeRows.length)}"/></worksheet>`; }
export function makeWorkbook(sheets = []) { const valid = sheets.length ? sheets : [{ name: 'Data', rows: [] }]; const workbookSheets = valid.map((sheet, i) => `<sheet name="${xmlEscape(String(sheet.name || `Sheet${i + 1}`).slice(0,31))}" sheetId="${i + 1}" r:id="rId${i + 1}"/>`).join(''); const rels = valid.map((_, i) => `<Relationship Id="rId${i + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i + 1}.xml"/>`).join(''); const content = [`<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>`, `<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>`, ...valid.map((_, i) => `<Override PartName="/xl/worksheets/sheet${i + 1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`)].join(''); const files = { '[Content_Types].xml': `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/>${content}</Types>`, '_rels/.rels': `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`, 'xl/workbook.xml': `<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><workbookPr date1904="false"/><sheets>${workbookSheets}</sheets></workbook>`, 'xl/_rels/workbook.xml.rels': `<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${rels}</Relationships>`, 'xl/styles.xml': `<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="solid"><fgColor rgb="D1FAE5"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/><xf numFmtId="0" fontId="1" fillId="1" borderId="0" applyFont="1" applyFill="1"/></cellXfs></styleSheet>`, ...Object.fromEntries(valid.map((sheet, i) => [`xl/worksheets/sheet${i + 1}.xml`, sheetXml(sheet.rows)])) }; return zipStore(files); }
export function exportWorkbook(filename, sheets) { const bytes = makeWorkbook(sheets); downloadBlob(new Blob([bytes], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }), filename.endsWith('.xlsx') ? filename : `${filename}.xlsx`); }
export function exportRows(filename, sheetName, headers, rows) { exportWorkbook(filename, [{ name: sheetName, rows: [headers, ...rows] }]); }
export function recordsToRows(records, columns) { return records.map(record => columns.map(column => typeof column.value === 'function' ? column.value(record) : record[column.key] ?? '')); }
export function exportRecords(filename, sheetName, records, columns) { exportRows(filename, sheetName, columns.map(c => c.label), recordsToRows(records, columns)); }
