import { db } from './database.js';
import { t } from './translations.js';
import { esc, attr, formatDate, formatNumber, badge, actionButtons, printTable, todayISO } from './utils.js';
import { moduleHeader, toolbar, tableHtml, openEntityForm, openRecordDetails, removeEntity, memberSelectOptions, madrasaSelectOptions, memberNames, madrasaNames, idsOf, reportStatusOptions } from './moduleHelpers.js';
import { reportTypes, reportTypeLabel, generateReport } from './reportGenerator.js';

function fields(members,madrasas){return [{type:'section',label:'reports'},{key:'reportNumber',label:'reportNumber',required:true},{key:'title',label:'reportTitle',required:true},{key:'type',label:'reportType',type:'select',options:()=>reportTypes.map(x=>({value:x.value,label:t(x.labelKey,x.value)}))},{key:'date',label:'date',type:'date',required:true},{key:'preparedByIds',label:'preparedBy',type:'multi-select',options:()=>memberSelectOptions(members,'',true)},{key:'relatedMembers',label:'relatedMember',type:'multi-select',options:()=>memberSelectOptions(members)},{key:'relatedMadrasas',label:'relatedMadrasa',type:'multi-select',options:()=>madrasaSelectOptions(madrasas)},{key:'subject',label:'subject'},{key:'introduction',label:'introduction',type:'textarea',span:2},{key:'objectives',label:'objectives',type:'textarea'},{key:'activities',label:'activitiesText',type:'textarea'},{key:'statistics',label:'statisticsText',type:'textarea'},{key:'findings',label:'findings',type:'textarea'},{key:'problems',label:'problems',type:'textarea'},{key:'analysis',label:'analysis',type:'textarea'},{key:'recommendations',label:'recommendations',type:'textarea'},{key:'conclusion',label:'conclusionText',type:'textarea'},{key:'followUp',label:'followUp',type:'textarea'},{key:'status',label:'status',type:'select',options:reportStatusOptions,default:'draft'},{key:'notes',label:'notes',type:'textarea',span:2}];}

export async function render(ctx){
  const [reports,members,madrasas]=await Promise.all(['reports','members','madrasas'].map(s=>db.getAll(s))); const q=ctx.params?.q||'';
  const filtered=q?reports.filter(r=>[r.reportNumber,r.title,r.subject,r.status].some(v=>String(v||'').toLocaleLowerCase().includes(q.toLocaleLowerCase()))):reports;
  const builder=`<section class="card" style="margin-bottom:17px"><div class="card-head"><div><h2>${esc(t('reportBuilder'))}</h2><p>${esc(t('generateReport'))} · ${esc(t('systemInfo'))}</p></div></div><div class="card-body"><form id="report-builder" class="form-grid four-col"><label class="field"><span>${esc(t('reportType'))}</span><select name="reportType">${reportTypes.map(x=>`<option value="${attr(x.value)}" ${ctx.params?.reportType===x.value?'selected':''}>${esc(t(x.labelKey,x.value))}</option>`).join('')}</select></label><label class="field"><span>${esc(t('fromDate'))}</span><input type="text" inputmode="numeric" class="solar-date-input" data-solar-date name="from" placeholder="${attr(t('solarDatePlaceholder'))}" maxlength="10"></label><label class="field"><span>${esc(t('toDate'))}</span><input type="text" inputmode="numeric" class="solar-date-input" data-solar-date name="to" placeholder="${attr(t('solarDatePlaceholder'))}" maxlength="10"></label><label class="field"><span>${esc(t('academicYearFilter'))}</span><input name="academicYear" value="${attr(ctx.settings?.academicYear||'')}"></label><label class="field"><span>${esc(t('filterByMember'))}</span><select name="member"><option value="">${esc(t('allMembers'))}</option>${memberSelectOptions(members).map(o=>`<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select></label><label class="field"><span>${esc(t('filterByMadrasa'))}</span><select name="madrasa"><option value="">${esc(t('allMadrasas'))}</option>${madrasaSelectOptions(madrasas).map(o=>`<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select></label><label class="field"><span>${esc(t('filterByStatus'))}</span><select name="status"><option value="">${esc(t('all'))}</option>${reportStatusOptions().map(o=>`<option value="${attr(o.value)}">${esc(o.label)}</option>`).join('')}</select></label><label class="field"><span>${esc(t('activityType'))}</span><select name="activityType"><option value="">${esc(t('all'))}</option>${['monitoringVisit','teacherTraining','seminar','workshop','meeting','consultation','teacherSupport','assessment','coordination','other'].map(k=>`<option value="${attr(k)}">${esc(t(k))}</option>`).join('')}</select></label><div class="form-actions"><button class="btn primary" type="submit">▤ ${esc(t('generateReport'))}</button><button class="btn outline" type="button" data-report-action="create">＋ ${esc(t('createReport'))}</button></div></form></div></section>`;
  const rows=filtered.slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))).map(r=>`<tr data-row-search="${attr([r.reportNumber,r.title,r.subject,r.status].join(' '))}"><td><strong>${esc(r.reportNumber||'—')}</strong><small>${esc(r.title||'')}</small></td><td>${esc(reportTypeLabel(r.type)||'—')}</td><td>${esc(formatDate(r.date))}</td><td>${esc(memberNames(members,r,'preparedByIds','preparedById'))}</td><td>${esc(madrasaNames(madrasas,r,'relatedMadrasas','relatedMadrasa'))}</td><td>${badge(t(r.status,r.status||'—'))}</td><td>${actionButtons(r.id,{store:'reports'})}</td></tr>`);
  return `${moduleHeader('reports',`${formatNumber(reports.length)} ${t('reports')}`,`<button class="btn primary" data-report-action="create">＋ ${esc(t('createReport'))}</button><button class="btn outline" data-report-action="print">⎙ ${esc(t('print'))}</button><button class="btn outline" data-report-action="export">⇩ ${esc(t('exportExcel'))}</button>`)}${builder}<section class="card">${toolbar(t('search'))}${tableHtml([t('reportNumber'),t('reportType'),t('date'),t('preparedBy'),t('relatedMadrasa'),t('status'),t('actions')],rows,t('noData'),`<button class="btn primary small" data-report-action="create">＋ ${esc(t('createReport'))}</button>`)}</section>`;
}
export async function bind(ctx,root){root.querySelector('[data-module-search]')?.addEventListener('input',e=>{const q=e.target.value.toLocaleLowerCase();root.querySelectorAll('[data-row-search]').forEach(row=>row.style.display=row.dataset.rowSearch.toLocaleLowerCase().includes(q)?'':'none');});root.querySelector('#report-builder')?.addEventListener('submit',async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target).entries());try{const result=await generateReport(ctx,data);ctx.printOfficial(result.title,result.body);}catch(err){console.error(err);ctx.notify(t('error'),'error');}});root.addEventListener('click',async e=>{const el=e.target.closest('[data-report-action]');if(el){const action=el.dataset.reportAction;if(action==='create')return openReport(ctx);if(action==='export')return ctx.export('reports');if(action==='print'){const rows=await db.getAll('reports');return ctx.printOfficial(t('reports'),`<div class="print-section"><h3>${esc(t('reports'))}</h3>${printTable([t('reportNumber'),t('reportTitle'),t('reportType'),t('date'),t('status')],rows.map(r=>[r.reportNumber,r.title,reportTypeLabel(r.type),formatDate(r.date),t(r.status,r.status)]))}</div>`);}}const btn=e.target.closest('[data-action]');if(!btn)return;const action=btn.dataset.action,id=btn.dataset.id;if(action==='view')return openRecordDetails(ctx,'reports',id);if(action==='edit')return openReport(ctx,id);if(action==='delete')return removeEntity(ctx,'reports',id);});}
async function openReport(ctx,id=''){const [reports,members,madrasas]=await Promise.all(['reports','members','madrasas'].map(s=>db.getAll(s)));const source=id?reports.find(r=>r.id===id)||{}:{};const record={...source,date:source.date||todayISO(),reportNumber:source.reportNumber||`R-${todayISO().slice(0,4)}-${String(reports.length+1).padStart(3,'0')}`,status:source.status||'draft',preparedByIds:idsOf(source,'preparedByIds','preparedById'),relatedMembers:idsOf(source,'relatedMembers','relatedMember'),relatedMadrasas:idsOf(source,'relatedMadrasas','relatedMadrasa')};return openEntityForm(ctx,{store:'reports',title:id?`${t('edit')} · ${t('reports')}`:t('createReport'),record,fields:fields(members,madrasas),wide:true,beforeSave:data=>{data.preparedByIds=Array.isArray(data.preparedByIds)?data.preparedByIds.filter(Boolean):[];data.preparedById=data.preparedByIds[0]||'';data.relatedMembers=Array.isArray(data.relatedMembers)?data.relatedMembers.filter(Boolean):[];data.relatedMember=data.relatedMembers[0]||'';data.relatedMadrasas=Array.isArray(data.relatedMadrasas)?data.relatedMadrasas.filter(Boolean):[];data.relatedMadrasa=data.relatedMadrasas[0]||'';return data;}});}
export async function autoAdd(ctx){return openReport(ctx);}
